# Generated by Django 5.2.7 on 2026-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0035_dispute_dispute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('withdrawn', 'Withdrawn')], default='open', max_length=20),
        ),
    ]
