# Generated by Django 5.2.7 on 2026-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("task_abandonment", "Task Abandonment (Penalty)"),
                    ("initial_points", "Initial Points"),
                ],
                max_length=20,
            ),
        ),
    ]
