# Generated by Django 5.2.7 on 2026-09-12 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="appeal_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_appeals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_status",
            field=models.CharField(
                choices=[
                    ("none", "No Appeal"),
                    ("appealed", "Appealed"),
                    ("upheld", "Upheld"),
                    ("overturned", "Overturned"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appealed_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("poster_wins", "Poster Wins"),
                    ("taker_wins", "Taker Wins"),
                    ("split", "Split Decision"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("appealed", "Appealed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_resolution", "Dispute Resolution"),
                    ("dispute_reversal", "Dispute Reversal"),
                ],
                max_length=30,
            ),
        ),
    ]
