# Generated by Django 5.2.7 on 2026-07-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
