# Generated by Django 5.2.7 on 2026-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="closeness",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="closeness",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
