# Generated by Django 5.2.7 on 2026-09-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="deposit_status",
            field=models.CharField(
                choices=[
                    ("held", "Held"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="held",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit_hold", "Dispute Deposit Hold"),
                    ("dispute_deposit_refund", "Dispute Deposit Refund"),
                    ("dispute_bond_forfeiture", "Dispute Bond Forfeiture"),
                ],
                max_length=50,
            ),
        ),
    ]
