# Generated by Django 5.2.7 on 2026-09-12 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="appeal_filed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_filed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filed_appeals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_resolution_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("overturned", "Overturned"),
                ],
                default="none",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_ruling",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("under_appeal", "Under Appeal"),
                    ("appeal_closed", "Appeal Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_settlement", "Dispute Settlement"),
                    ("dispute_payout", "Dispute Payout"),
                    ("dispute_refund", "Dispute Refund"),
                    ("dispute_split", "Dispute Split"),
                    ("appeal_payout", "Appeal Payout"),
                    ("appeal_refund", "Appeal Refund"),
                    ("dispute_settlement_poster", "Dispute Settlement Poster"),
                    ("dispute_settlement_taker", "Dispute Settlement Taker"),
                ],
                max_length=50,
            ),
        ),
    ]
