# Generated by Django 5.2.7 on 2026-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="category",
            field=models.CharField(
                choices=[
                    ("quality_issue", "Quality Issue"),
                    ("incomplete_work", "Incomplete Work"),
                    ("unresponsive_partner", "Unresponsive Partner"),
                    ("payment_dispute", "Payment Dispute"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_details",
            field=models.TextField(blank=True, default=""),
        ),
    ]
