# Generated by Django 5.2.7 on 2026-09-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="taker_collateral",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("collateral_lock", "Collateral Lock"),
                    ("collateral_release", "Collateral Release"),
                    ("collateral_slashed", "Collateral Slashed"),
                ],
                max_length=20,
            ),
        ),
    ]
