# Generated by Django 5.2.7 on 2026-09-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("collateral_lock", "Collateral Lock (Points Locked)"),
                    ("collateral_release", "Collateral Release (Points Returned)"),
                    ("collateral_refund", "Collateral Refund (Points Returned)"),
                    ("collateral_slash", "Collateral Slash (Penalty Deducted)"),
                ],
                max_length=20,
            ),
        ),
    ]
