# Generated by Django 5.2.7 on 2026-09-13 19:33

from django.db import migrations, models


def migrate_legacy_disputes(apps, schema_editor):
    Dispute = apps.get_model('basic', 'Dispute')
    Dispute.objects.filter(status='open').update(status='evidence_submission')

class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="appeal_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="voting_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("evidence_submission", "Evidence Submission"),
                    ("voting", "Voting"),
                    ("appealed", "Appealed"),
                    ("resolved", "Resolved"),
                    ("cancelled", "Cancelled"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_legacy_disputes, reverse_code=migrations.RunPython.noop),
    ]
