# Generated by Django 5.2.7 on 2026-09-10 22:22

import basic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="dispute_stage",
            field=models.CharField(
                choices=[
                    ("initial_proof", "Initial Proof Submitted"),
                    ("counter_evidence", "Awaiting Counter-Evidence"),
                    ("under_review", "Under Review"),
                    ("resolved", "Resolved"),
                    ("timed_out", "Timed Out"),
                ],
                default="initial_proof",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_outcome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="response_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_settlement", "Dispute Settlement"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dispute_evidence/",
                        validators=[basic.models.validate_evidence_file],
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("initial_proof", "Initial Proof"),
                            ("counter_evidence", "Counter-Evidence"),
                            ("supplemental", "Supplemental Evidence"),
                        ],
                        default="initial_proof",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="basic.dispute",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_evidences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
