# Generated by Django 5.2.7 on 2026-09-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="doer_payout",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_refund",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_payout", "Dispute Payout"),
                    ("dispute_refund", "Dispute Refund"),
                    ("dispute_split", "Dispute Split Settlement"),
                    ("dispute_settlement", "Dispute Settlement"),
                    ("dispute_settlement_poster", "Dispute Settlement (Poster)"),
                    ("dispute_settlement_taker", "Dispute Settlement (Taker)"),
                ],
                max_length=50,
            ),
        ),
    ]
