# Generated by Django 5.2.7 on 2026-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="deposit_amount",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit (Points Held)"),
                    ("dispute_refund", "Dispute Deposit Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
