# Generated by Django 5.2.7 on 2026-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0042_remove_dispute_dispute_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardledger",
            name="currency",
            field=models.CharField(
                choices=[("points", "Points"), ("usd", "USD")],
                default="points",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reward_type",
            field=models.CharField(
                choices=[("points", "Points"), ("usd", "USD")],
                default="points",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="stripe_refund_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="stripe_transfer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
