# Generated by Django 5.2.7 on 2026-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("evidence_submission", "Evidence Submission"),
                    ("voting_period", "Voting Period"),
                    ("appeal_period", "Appeal Period"),
                    ("resolved", "Resolved"),
                    ("cancelled", "Cancelled"),
                ],
                default="evidence_submission",
                max_length=30,
            ),
        ),
    ]
