# Generated by Django 5.2.7 on 2026-09-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non_completion", "Non-Completion"),
                    ("quality_issue", "Quality Issue"),
                    ("payment_dispute", "Payment Dispute"),
                    ("communication_failure", "Communication Failure"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_payload",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
