# Generated by Django 5.2.7 on 2026-09-26 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="consensus_outcome",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="counter_bond_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_escrow_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Counter-Bond"),
                    ("held", "Held in Escrow"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="voting_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="worker_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="worker_escrow_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Counter-Bond"),
                    ("held", "Held in Escrow"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="held",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="escrow_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Counter-Bond"),
                    ("held", "Held in Escrow"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="held",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("dispute_poster_deposit", "Poster Dispute Deposit Bond Held"),
                    ("juror_stake", "Juror Stake Held"),
                    ("juror_stake_refund", "Juror Stake Refunded"),
                    ("juror_slash", "Juror Stake Slashed"),
                    ("juror_reward", "Consensus Jury Reward Distributed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="JurorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("has_voted", models.BooleanField(default=False)),
                ("vote_choice", models.CharField(blank=True, max_length=20, null=True)),
                ("stake_amount", models.PositiveIntegerField(default=25)),
                (
                    "stake_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("held", "Held in Escrow"),
                            ("refunded", "Refunded"),
                            ("slashed", "Slashed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror")},
            },
        ),
    ]
