# Generated by Django 5.2.7 on 2026-09-25 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="assigned_jurors",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="final_winner",
            field=models.CharField(
                blank=True,
                choices=[("poster", "Poster Wins"), ("taker", "Taker Wins")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="primary_outcome",
            field=models.CharField(
                blank=True,
                choices=[("poster", "Poster Wins"), ("taker", "Taker Wins")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="primary_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="senior_outcome",
            field=models.CharField(
                blank=True,
                choices=[("poster", "Poster Wins"), ("taker", "Taker Wins")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="juror_ineligible_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open / Primary Voting"),
                    ("primary_resolved", "Primary Resolved (Appeal Window)"),
                    ("appealed", "Appealed / Senior Review"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("appeal_bond_held", "Appeal Bond Escrow Held"),
                    ("appeal_bond_refund", "Appeal Bond Refunded"),
                    ("appeal_bond_forfeit", "Appeal Bond Forfeited"),
                    ("juror_slash", "Bad-Faith Juror Slashed"),
                    ("juror_reward", "Honest Juror Reward"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DisputeAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bond_amount", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Senior Panel"),
                            ("upheld", "Appeal Upheld"),
                            ("rejected", "Appeal Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appellant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeal",
                        to="basic.dispute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisputeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Jury"),
                            ("senior", "Senior Appeal Panel"),
                        ],
                        default="primary",
                        max_length=10,
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("poster", "Poster Wins"), ("taker", "Taker Wins")],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror", "tier")},
            },
        ),
    ]
