# Generated by Django 5.2.7 on 2026-09-16 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="evidence_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="voting_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("EVIDENCE_SUBMISSION", "Evidence Submission"),
                    ("JURY_SELECTION", "Jury Selection"),
                    ("VOTING_ACTIVE", "Voting Active"),
                    ("CONSENSUS_REACHED", "Consensus Reached"),
                    ("RESOLVED", "Resolved"),
                    ("EXPIRED_FALLBACK", "Expired Fallback"),
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="EVIDENCE_SUBMISSION",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_settlement", "Dispute Settlement"),
                    ("dispute_payout", "Dispute Payout"),
                    ("dispute_refund", "Dispute Refund"),
                    ("dispute_split", "Dispute Split Payout"),
                    ("dispute_settlement_poster", "Dispute Settlement Poster"),
                    ("dispute_settlement_taker", "Dispute Settlement Taker"),
                    ("juror_stake", "Juror Stake"),
                    ("juror_reward", "Juror Reward"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="dispute_evidence/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_entries",
                        to="basic.dispute",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_evidences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisputeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            ("poster", "Poster"),
                            ("taker", "Taker"),
                            ("split", "Split"),
                        ],
                        max_length=20,
                    ),
                ),
                ("staked_amount", models.IntegerField(default=10)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror")},
            },
        ),
        migrations.CreateModel(
            name="JuryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("has_staked", models.BooleanField(default=False)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_assignments",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror")},
            },
        ),
    ]
