# Generated by Django 5.2.7 on 2026-09-29 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="dispute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="basic.dispute",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_deliberation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dispute",
            name="jurors",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
