# Generated by Django 5.2.7 on 2026-09-26 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="jurors",
            field=models.ManyToManyField(
                blank=True, related_name="juror_disputes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
