# Generated by Django 5.2.7 on 2026-09-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="disputes_lost",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disputes_won",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reputation_score",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="risk_tier",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Risk"),
                    ("MEDIUM", "Medium Risk"),
                    ("HIGH", "High Risk"),
                ],
                default="LOW",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_cancelled",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_posted",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
