# Generated by Django 5.2.7 on 2026-09-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="settlement_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dispute",
            name="settlement_taker_share_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("dispute_partial_payout", "Dispute Partial Payout"),
                    ("dispute_partial_refund", "Dispute Partial Refund"),
                ],
                max_length=50,
            ),
        ),
    ]
