# Generated by Django 5.2.7 on 2026-09-24 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Commit Phase"),
                    ("commit", "Commit Phase"),
                    ("reveal", "Reveal Phase"),
                    ("resolved", "Resolved"),
                ],
                default="commit",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DisputeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(max_length=64)),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
                ("revealed", models.BooleanField(default=False)),
                (
                    "revealed_vote",
                    models.CharField(
                        blank=True,
                        choices=[("poster", "Poster"), ("taker", "Taker")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.dispute",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "voter")},
            },
        ),
    ]
