# Generated by Django 5.2.7 on 2026-09-21 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("juror_reward", "Jury Duty Reward Awarded"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Jury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("selecting", "Selecting"),
                            ("voting", "Voting"),
                            ("concluded", "Concluded"),
                        ],
                        default="selecting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "dispute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury",
                        to="basic.dispute",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_juries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JurorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("voted", "Voted"),
                            ("expired", "Expired"),
                            ("replaced", "Replaced"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("reward_paid", models.BooleanField(default=False)),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="basic.jury",
                    ),
                ),
            ],
            options={
                "unique_together": {("jury", "juror")},
            },
        ),
        migrations.CreateModel(
            name="JuryVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.jury",
                    ),
                ),
                (
                    "voted_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_votes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("jury", "juror")},
            },
        ),
    ]
