# Generated by Django 5.2.7 on 2026-09-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="category",
            field=models.CharField(
                choices=[
                    ("non_completion", "Non Completion"),
                    ("quality_issue", "Quality Issue"),
                    ("late_delivery", "Late Delivery"),
                    ("unresponsive", "Unresponsive"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
