# Generated by Django 5.2.7 on 2026-09-24 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="counter_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="initiator_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("pending_counter_deposit", "Pending Counter-Deposit"),
                    ("active_voting", "Active Voting"),
                    ("resolved", "Resolved"),
                ],
                default="pending_counter_deposit",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("counter_dispute_deposit", "Counter Dispute Deposit Bond Held"),
                    ("juror_stake", "Juror Vote Stake Deducted"),
                    ("juror_slash", "Juror Vote Stake Slashed"),
                    ("juror_reward", "Juror Vote Reward Payout"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DisputeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stake_amount", models.PositiveIntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.dispute",
                    ),
                ),
                (
                    "voted_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_votes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "voter")},
            },
        ),
    ]
