# Generated by Django 5.2.7 on 2026-09-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("evidence_submission", "Evidence Submission"),
                    ("juror_deliberation", "Juror Deliberation"),
                    ("voting", "Voting"),
                    ("appealed", "Appealed"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=30,
            ),
        ),
    ]
