# Generated by Django 5.2.7 on 2026-09-21 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("under_appeal", "Under Appeal"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("appeal_deposit", "Appeal Deposit Bond Held"),
                    ("appeal_refund", "Appeal Deposit Bond Refunded"),
                    ("appeal_slash", "Litigant Deposit Bond Slashed"),
                    ("juror_reward", "Honest Juror Reward Payout"),
                    ("juror_slash", "Dishonest Juror Points Slashed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("disputed", "Disputed"),
                    ("cancelled", "Cancelled"),
                    ("under_appeal", "Under Appeal"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appeal_deposit", models.PositiveIntegerField(default=0)),
                ("round_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Juror Votes"),
                            ("resolved", "Resolved"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ruling",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("upheld", "Upheld (Appellant Won)"),
                            ("overturned", "Overturned (Appellant Lost)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("consensus_threshold", models.FloatField(default=0.66)),
                ("quorum", models.PositiveIntegerField(default=3)),
                (
                    "appellant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filed_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to="basic.dispute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppealJuror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("poster", "In favor of Poster"),
                            ("taker", "In favor of Taker"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("is_slashed", models.BooleanField(default=False)),
                ("is_rewarded", models.BooleanField(default=False)),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to="basic.appeal",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("appeal", "juror")},
            },
        ),
    ]
