# Generated by Django 5.2.7 on 2026-09-17 01:57

import basic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="evidence_deadline",
            field=models.DateTimeField(default=basic.models.default_evidence_deadline),
        ),
        migrations.AddField(
            model_name="dispute",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dispute_evidence/",
                        validators=[basic.models.validate_evidence_file],
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Note"),
                            ("document", "Document"),
                            ("image", "Image"),
                            ("counter_evidence", "Counter Evidence"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="basic.dispute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_evidences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
