# Generated by Django 5.2.7 on 2026-09-27 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="conversation_type",
            field=models.CharField(
                choices=[
                    ("main", "Main Task Chat"),
                    ("deliberation", "Juror Deliberation"),
                ],
                default="main",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="dispute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="basic.dispute",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="jurors",
            field=models.ManyToManyField(
                blank=True, related_name="juror_disputes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="conversations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="basic.task",
            ),
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="dispute_evidences/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="basic.dispute",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_evidences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
