# Generated by Django 5.2.7 on 2026-09-21 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("RAISED", "Raised"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("RESOLVED", "Resolved"),
                            ("ESCROW_REFUNDED", "Escrow Refunded"),
                            ("ESCROW_FORFEITED", "Escrow Forfeited"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("new_status", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="basic.dispute",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
