# Generated by Django 5.2.7 on 2026-09-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="category",
            field=models.CharField(
                choices=[
                    ("incomplete_work", "Incomplete Work"),
                    ("quality_issue", "Quality Defect"),
                    ("unresponsive_partner", "Unresponsive Partner"),
                    ("payment_dispute", "Payment Dispute"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("screenshot", "Screenshot / Image"),
                    ("document", "Document"),
                    ("chat_log", "Chat Log"),
                    ("link", "External Link"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
