# Generated by Django 5.2.7 on 2026-09-17 20:03

import basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="voting_deadline",
            field=models.DateTimeField(
                blank=True, default=basic.models.default_voting_deadline, null=True
            ),
        ),
    ]
