# Generated by Django 5.2.7 on 2026-09-24 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JuryPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_size", models.PositiveIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("resolved", "Resolved"),
                            ("insufficient_jurors", "Insufficient Jurors"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_pool",
                        to="basic.dispute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JurorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        blank=True,
                        choices=[("poster", "Poster"), ("worker", "Worker")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jury_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="basic.jurypool",
                    ),
                ),
            ],
            options={
                "unique_together": {("jury_pool", "juror")},
            },
        ),
    ]
