# Generated by Django 5.2.7 on 2026-09-18 22:04

from datetime import timedelta
from django.db import migrations, models
from django.utils import timezone


def populate_voting_deadlines(apps, schema_editor):
    Dispute = apps.get_model("basic", "Dispute")
    for dispute in Dispute.objects.filter(voting_deadline__isnull=True):
        period = getattr(dispute, "voting_period_days", None) or 7
        if dispute.created_at:
            dispute.voting_deadline = dispute.created_at + timedelta(days=period)
        else:
            dispute.voting_deadline = timezone.now() + timedelta(days=period)
        dispute.save(update_fields=["voting_deadline"])


def reverse_populate_voting_deadlines(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="voting_deadline",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="voting_period_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.RunPython(
            populate_voting_deadlines,
            reverse_code=reverse_populate_voting_deadlines,
        ),
    ]
