# Generated by Django 5.2.7 on 2026-09-20 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="appeal_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_escrow_status",
            field=models.CharField(
                choices=[
                    ("held", "Held in Escrow"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="held",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_window_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_appeals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="consensus_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="consensus_reached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dispute",
            name="stage",
            field=models.CharField(
                choices=[("initial", "Initial Panel"), ("senior", "Senior Panel")],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="winning_choice",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("pending_consensus", "Pending Consensus"),
                    ("appealed", "Appealed"),
                    ("senior_review", "Senior Review"),
                    ("resolved", "Resolved"),
                    ("slashed", "Slashed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("appeal_deposit", "Appeal Deposit Bond Held"),
                    ("appeal_refund", "Appeal Deposit Bond Refunded"),
                    ("appeal_forfeit", "Appeal Deposit Bond Forfeited"),
                    ("slashing_penalty", "Slashing Penalty Deducted"),
                    ("slashing_reward", "Slashing Reward Awarded"),
                    ("juror_stake", "Juror Stake Held"),
                    ("juror_slash", "Juror Stake Slashed"),
                    ("juror_reward", "Juror Reward Awarded"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DisputeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Panel"),
                            ("senior", "Senior Panel"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("poster", "Poster"), ("taker", "Taker")],
                        max_length=20,
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.dispute",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "voter", "stage")},
            },
        ),
        migrations.CreateModel(
            name="JuryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Panel"),
                            ("senior", "Senior Panel"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("staked_amount", models.PositiveIntegerField(default=50)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_assignments",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror")},
            },
        ),
    ]
