# Generated by Django 5.2.7 on 2026-09-20 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="juror_pool_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("posted_by", "In Favor of Task Poster"),
                    ("taken_by", "In Favor of Task Assignee"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DisputeJuror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted_by", "In Favor of Task Poster"),
                            ("taken_by", "In Favor of Task Assignee"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurors",
                        to="basic.dispute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "user")},
            },
        ),
    ]
