# Generated by Django 5.2.7 on 2026-09-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="taker_collateral",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("taker_collateral_deposit", "Taker Collateral Deposit"),
                    ("taker_collateral_refund", "Taker Collateral Refund"),
                    ("taker_collateral_slash", "Taker Collateral Slash"),
                ],
                max_length=50,
            ),
        ),
    ]
