# Generated by Django 5.2.7 on 2026-09-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="counter_bond_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_escrow_status",
            field=models.CharField(
                choices=[
                    ("held", "Held in Escrow"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="held",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="voting_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="worker_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="worker_escrow_status",
            field=models.CharField(
                choices=[
                    ("held", "Held in Escrow"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="held",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("voting", "Voting"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("poster_counter_bond", "Poster Counter-Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("juror_stake", "Juror Stake Held"),
                    ("juror_stake_refund", "Juror Stake Refunded"),
                    ("juror_reward", "Juror Reward Payout"),
                    ("juror_slash", "Juror Stake Slashed"),
                    ("dispute_payout", "Dispute Winner Award"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DisputeVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("poster", "Poster / Reclaim"),
                            ("worker", "Worker / Complete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stake_amount", models.PositiveIntegerField(default=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.dispute",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "voter")},
            },
        ),
    ]
