# Generated by Django 5.2.7 on 2026-09-20 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury",
                        to="basic.dispute",
                    ),
                ),
                (
                    "jurors",
                    models.ManyToManyField(
                        related_name="jury_panels", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JuryVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("poster_wins", "Poster Wins"),
                            ("taker_wins", "Taker Wins"),
                        ],
                        max_length=20,
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.jury",
                    ),
                ),
            ],
            options={
                "unique_together": {("jury", "juror")},
            },
        ),
    ]
