# Generated by Django 5.2.7 on 2026-09-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="disputes_lost_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disputes_won_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reputation_score",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="risk_level",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="LOW",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_completed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_defaulted_count",
            field=models.IntegerField(default=0),
        ),
    ]
