# Generated by Django 5.2.7 on 2026-09-22 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("juror_reward", "Juror Reward Points"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="JuryPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("voting", "Voting in Progress"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="voting",
                        max_length=20,
                    ),
                ),
                ("voting_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury_panel",
                        to="basic.dispute",
                    ),
                ),
                (
                    "jurors",
                    models.ManyToManyField(
                        related_name="assigned_jury_panels", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JurorVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("poster", "In favor of Task Poster"),
                            ("taker", "In favor of Task Taker"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.jurypanel",
                    ),
                ),
            ],
            options={
                "unique_together": {("panel", "juror")},
            },
        ),
    ]
