# Generated by Django 5.2.7 on 2026-09-24 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("juror_stake", "Juror Stake Held"),
                    ("juror_reward", "Juror Reward Payout"),
                    ("juror_slash", "Juror Stake Slashed"),
                    ("juror_stake_refund", "Juror Stake Refunded"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Jury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("voting", "Voting"),
                            ("resolved", "Resolved"),
                            ("fallback", "Fallback to Staff"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "consensus_outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("poster_win", "Poster Wins"),
                            ("taker_win", "Taker Wins"),
                            ("draw", "Draw / Split"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("consensus_reached", models.BooleanField(default=False)),
                ("quorum_required", models.PositiveIntegerField(default=3)),
                ("supermajority_threshold", models.FloatField(default=0.66)),
                ("voting_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jury",
                        to="basic.dispute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Juror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("staked_amount", models.PositiveIntegerField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("voted", "Voted"),
                            ("slashed", "Slashed"),
                            ("rewarded", "Rewarded"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurors",
                        to="basic.jury",
                    ),
                ),
            ],
            options={
                "unique_together": {("jury", "user")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("poster", "Poster Wins"), ("taker", "Taker Wins")],
                        max_length=10,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("reasoning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.juror",
                    ),
                ),
                (
                    "jury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="basic.jury",
                    ),
                ),
            ],
            options={
                "unique_together": {("jury", "juror")},
            },
        ),
    ]
