# Generated by Django 5.2.7 on 2026-09-24 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="appeal_bond_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_escrow_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("held", "Held in Escrow"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appeals_raised",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="consensus_outcome",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="dispute",
            name="tier",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="dispute",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disputes_lost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disputes_won",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="locked_collateral",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reputation_score",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_abandoned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_cancelled",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("evidence_submission", "Evidence Submission"),
                    ("voting", "Voting"),
                    ("under_review", "Under Review"),
                    ("appealed", "Appealed"),
                    ("under_appeal", "Under Appeal"),
                    ("resolved", "Resolved"),
                    ("appeal_upheld", "Appeal Upheld"),
                    ("appeal_reversed", "Appeal Reversed"),
                    ("withdrawn", "Withdrawn"),
                    ("slashed", "Slashed"),
                    ("staff_review", "Staff Review"),
                ],
                default="open",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("juror_stake_lock", "Juror Stake Locked"),
                    ("juror_stake_refunded", "Juror Stake Refunded"),
                    ("juror_stake_slash", "Juror Stake Slashed"),
                    ("juror_reward_payout", "Juror Reward Payout"),
                    ("dispute_appeal_bond", "Dispute Appeal Stake Bond Held"),
                    ("dispute_appeal_refund", "Dispute Appeal Stake Bond Refunded"),
                    ("dispute_appeal_forfeit", "Dispute Appeal Stake Bond Forfeited"),
                    ("juror_slashing", "Dishonest Juror Slashing Penalty"),
                    ("slash_penalty", "Slash Penalty"),
                    ("appeal_fee", "Appeal Fee"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DisputeAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="basic.dispute",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="JurorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.IntegerField(default=1)),
                ("stake_amount", models.PositiveIntegerField(default=50)),
                ("has_voted", models.BooleanField(default=False)),
                ("vote", models.CharField(blank=True, default="", max_length=20)),
                (
                    "voting_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Vote"),
                            ("voted", "Voted"),
                            ("slashed", "Slashed"),
                            ("rewarded", "Rewarded"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror")},
            },
        ),
    ]
