# Generated by Django 5.2.7 on 2026-09-23 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="commit_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="jurors",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="reveal_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="voting_phase",
            field=models.CharField(
                choices=[
                    ("commit", "Commit Phase"),
                    ("reveal", "Reveal Phase"),
                    ("finished", "Finished"),
                ],
                default="commit",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DisputeCommitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commitment_hash", models.CharField(max_length=64)),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
                ("vote_choice", models.CharField(blank=True, max_length=50, null=True)),
                ("salt", models.CharField(blank=True, max_length=128, null=True)),
                ("revealed", models.BooleanField(default=False)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_commitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror")},
            },
        ),
    ]
