# Generated by Django 5.2.7 on 2026-09-17 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="appeal_decision",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_justification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_rationale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appeal_resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appeal_resolved_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="appealed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appealed_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_payout",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_decision",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_rationale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="taker_payout",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("pending_appeal", "Pending Appeal"),
                    ("appeal_closed", "Appeal Closed"),
                    ("appeal_upheld", "Appeal Upheld"),
                    ("appeal_reversed", "Appeal Reversed"),
                ],
                default="open",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_payout", "Dispute Payout"),
                    ("dispute_refund", "Dispute Refund"),
                    ("dispute_split", "Dispute Split"),
                    ("dispute_settlement", "Dispute Settlement"),
                    ("dispute_settlement_poster", "Dispute Settlement Poster"),
                    ("dispute_settlement_taker", "Dispute Settlement Taker"),
                    ("appeal_payout", "Appeal Payout"),
                    ("appeal_refund", "Appeal Refund"),
                    ("appeal_reversal", "Appeal Reversal"),
                ],
                max_length=50,
            ),
        ),
    ]
