# Generated by Django 5.2.7 on 2026-09-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="category",
            field=models.CharField(
                choices=[
                    ("non_delivery", "Non-Delivery"),
                    ("poor_quality", "Poor Quality"),
                    ("unresponsive_poster", "Unresponsive Poster"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence",
            field=models.TextField(blank=True, default=""),
        ),
    ]
