# Generated by Django 5.2.7 on 2026-09-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("resolved", "Resolved"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
