# Generated by Django 5.2.7 on 2026-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="disputes_lost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disputes_won",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reputation_score",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_abandoned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tasks_completed",
            field=models.IntegerField(default=0),
        ),
    ]
