# Generated by Django 5.2.7 on 2026-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incomplete_requirements", "Incomplete Requirements"),
                    ("unresponsive_counterparty", "Unresponsive Counterparty"),
                    ("deliverable_issue", "Deliverable Issue"),
                    ("payment_points_dispute", "Payment/Points Dispute"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="evidence_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
