# Generated by Django 5.2.7 on 2026-09-20 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispute",
            name="deposit_amount",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="escrow_status",
        ),
        migrations.AddField(
            model_name="dispute",
            name="consensus_outcome",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="dispute",
            name="counter_bond_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="poster_escrow_status",
            field=models.CharField(
                choices=[
                    ("held", "Held in Escrow"),
                    ("pending", "Pending Counter Bond"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="voting_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="worker_deposit_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dispute",
            name="worker_escrow_status",
            field=models.CharField(
                choices=[
                    ("held", "Held in Escrow"),
                    ("pending", "Pending Counter Bond"),
                    ("refunded", "Refunded"),
                    ("forfeited", "Forfeited"),
                ],
                default="held",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("voting", "In Juror Voting"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("dispute_poster_deposit", "Dispute Poster Deposit Bond Held"),
                    ("juror_stake_lock", "Juror Stake Locked for Dispute Vote"),
                    ("juror_stake_slash", "Juror Stake Slashed for Incorrect Vote"),
                    ("juror_reward_payout", "Juror Reward and Stake Refund"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="JurorVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("worker", "Favor Task Worker"),
                            ("poster", "Favor Task Poster"),
                        ],
                        max_length=10,
                    ),
                ),
                ("stake_amount", models.PositiveIntegerField()),
                ("is_slashed", models.BooleanField(default=False)),
                ("reward_amount", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_votes",
                        to="basic.dispute",
                    ),
                ),
                (
                    "juror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juror_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "juror")},
            },
        ),
    ]
