# Generated by Django 5.2.7 on 2026-09-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0043_dispute_deposit_amount_dispute_escrow_status_and_more"),
        ("basic", "0043_dispute_expires_at_dispute_resolution_reason_and_more"),
    ]

    operations = []
