# Generated by Django 5.2.7 on 2026-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0044_dispute_evidence_deadline_dispute_resolved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("task_creation", "Task Creation (Points Reserved)"),
                    ("task_completion", "Task Completion (Points Awarded)"),
                    ("task_cancellation", "Task Cancellation (Points Refunded)"),
                    ("initial_points", "Initial Points"),
                    ("dispute_deposit", "Dispute Deposit Bond Held"),
                    ("dispute_refund", "Dispute Deposit Bond Refunded"),
                    ("dispute_forfeit", "Dispute Deposit Bond Forfeited"),
                    ("dispute_settlement", "Dispute Settlement"),
                    ("dispute_payout", "Dispute Payout"),
                    ("dispute_split", "Dispute Split Payout"),
                    ("dispute_settlement_poster", "Dispute Settlement Poster"),
                    ("dispute_settlement_taker", "Dispute Settlement Taker"),
                    ("juror_stake", "Juror Stake"),
                    ("juror_reward", "Juror Reward"),
                ],
                max_length=50,
            ),
        ),
    ]
