# Generated by Django 5.2.7 on 2026-09-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0044_alter_dispute_status_disputevote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Commit Phase"),
                    ("commit", "Commit Phase"),
                    ("reveal", "Reveal Phase"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
